// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv5McI69BS8_OwJx5Sw0pZDPtDTELe5pc',
    appId: '1:886688963756:web:7ce282a6c41d7826fbd309',
    messagingSenderId: '886688963756',
    projectId: 'bdintegracion',
    authDomain: 'bdintegracion.firebaseapp.com',
    storageBucket: 'bdintegracion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCanbHomnxQg384lLWTA2RKmntLWjsvtzM',
    appId: '1:886688963756:android:3be98a8394d1aa35fbd309',
    messagingSenderId: '886688963756',
    projectId: 'bdintegracion',
    storageBucket: 'bdintegracion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwjXH5UiJFi_ciOvvHRR6o0l41vZ5l8MU',
    appId: '1:886688963756:ios:8f2502944d707184fbd309',
    messagingSenderId: '886688963756',
    projectId: 'bdintegracion',
    storageBucket: 'bdintegracion.firebasestorage.app',
    iosBundleId: 'com.example.dbintegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwjXH5UiJFi_ciOvvHRR6o0l41vZ5l8MU',
    appId: '1:886688963756:ios:8f2502944d707184fbd309',
    messagingSenderId: '886688963756',
    projectId: 'bdintegracion',
    storageBucket: 'bdintegracion.firebasestorage.app',
    iosBundleId: 'com.example.dbintegration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv5McI69BS8_OwJx5Sw0pZDPtDTELe5pc',
    appId: '1:886688963756:web:69000b7b3b2168cffbd309',
    messagingSenderId: '886688963756',
    projectId: 'bdintegracion',
    authDomain: 'bdintegracion.firebaseapp.com',
    storageBucket: 'bdintegracion.firebasestorage.app',
  );
}
